name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  npm-run:
    name: ${{ matrix.stage }}

    strategy:
      fail-fast: false

      matrix:
        stage: [lint, typecheck, test, package]

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          cache: pnpm

      - run: pnpm install

      - run: pnpm run ${{ matrix.stage }}
