name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  npm-run:
    name: ${{ matrix.stage }}

    strategy:
      fail-fast: false

      matrix:
        stage: [lint, typecheck, test, package]

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - run: npm ci

      - run: npm run ${{ matrix.stage }}
